export const posts = [
  {
    id: 1,
    slug: 'yellowstone-full-time-rv',
    category: 'Destinations',
    tag: 'Featured',
    title: "A Full Month in Yellowstone: Everything They Don't Tell You",
    excerpt: 'We parked our 32-foot Class A outside Gardiner, MT and spent four weeks chasing geysers, dodging bison traffic, and finding the campsite secrets locals guard closely.',
    image: 'https://images.unsplash.com/photo-1527489377706-5bf97e608852?w=900&q=80',
    author: 'Jake & Maria Rivera',
    authorAvatar: 'https://i.pravatar.cc/48?img=12',
    date: 'May 28, 2025',
    readTime: '9 min',
    likes: 347,
    comments: 42,
    sponsored: false,
  },
  {
    id: 2,
    slug: 'solar-panel-upgrade',
    category: 'Gear & Mods',
    tag: 'Popular',
    title: 'We Went Solar: An $1,800 Upgrade That Changed Everything',
    excerpt: 'Boondocking used to terrify us. After installing 800W of solar and a lithium battery bank, we stay off-grid for weeks. Exact parts list and total cost inside.',
    image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=900&q=80',
    author: 'Dale Hutchins',
    authorAvatar: 'https://i.pravatar.cc/48?img=33',
    date: 'May 14, 2025',
    readTime: '12 min',
    likes: 521,
    comments: 88,
    sponsored: false,
  },
  {
    id: 3,
    slug: 'florida-gulf-coast-spots',
    category: 'Destinations',
    tag: null,
    title: "Florida's Gulf Coast: 7 Hidden RV Spots That Still Feel Wild",
    excerpt: 'Beyond the crowded snowbird parks, Florida hides magical stretches of coast. These sites require research — and a real sense of adventure.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=80',
    author: 'Susan Morales',
    authorAvatar: 'https://i.pravatar.cc/48?img=47',
    date: 'May 3, 2025',
    readTime: '7 min',
    likes: 198,
    comments: 26,
    sponsored: false,
  },
  {
    id: 4,
    slug: 'best-rv-coffee-makers',
    category: 'Reviews',
    tag: 'Sponsored',
    title: '5 Best Coffee Makers for Your RV Kitchen (Tested on the Road)',
    excerpt: 'We tested nine coffee makers over three months. Counter space, power draw, and brew quality all matter when you live at 60mph.',
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=900&q=80',
    author: 'Jake & Maria Rivera',
    authorAvatar: 'https://i.pravatar.cc/48?img=12',
    date: 'April 22, 2025',
    readTime: '6 min',
    likes: 263,
    comments: 35,
    sponsored: true,
  },
  {
    id: 5,
    slug: 'rv-full-time-budget',
    category: 'Full-Time RV',
    tag: null,
    title: 'Our Actual Monthly Budget: Full-Time RVing on $2,700',
    excerpt: 'People always ask what full-time RV life really costs. Every dollar — fuel, campgrounds, repairs, food, insurance, and the surprises — broken down honestly.',
    image: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=900&q=80',
    author: 'Terri & Glen Bauer',
    authorAvatar: 'https://i.pravatar.cc/48?img=21',
    date: 'April 10, 2025',
    readTime: '11 min',
    likes: 712,
    comments: 114,
    sponsored: false,
  },
  {
    id: 6,
    slug: 'dispersed-camping-101',
    category: 'Tips & Tricks',
    tag: null,
    title: 'Dispersed Camping 101: Free Land, Zero Hookups, Total Freedom',
    excerpt: 'BLM and National Forest land lets you camp virtually anywhere for free. Here is how to find spots, what rules apply, and how to leave no trace.',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=900&q=80',
    author: 'Dale Hutchins',
    authorAvatar: 'https://i.pravatar.cc/48?img=33',
    date: 'March 30, 2025',
    readTime: '8 min',
    likes: 434,
    comments: 57,
    sponsored: false,
  },
];

export const categories = ['All', 'Destinations', 'Gear & Mods', 'Full-Time RV', 'Reviews', 'Tips & Tricks'];

export const affiliateProducts = [
  {
    id: 1,
    name: 'Jackery Explorer 2000 Pro',
    category: 'Power',
    price: '$1,799',
    rating: 4.8,
    reviews: 2341,
    desc: 'Our go-to portable power station. Handles everything in our rig for 3+ days without sun.',
    badge: "Editor's Pick",
    link: '#affiliate-jackery',
    emoji: '🔋',
  },
  {
    id: 2,
    name: 'Winegard ConnecT 2.0',
    category: 'Connectivity',
    price: '$379',
    rating: 4.5,
    reviews: 876,
    desc: 'Best WiFi extender we have tested. Works reliably in almost every campground.',
    badge: 'Best Value',
    link: '#affiliate-winegard',
    emoji: '📡',
  },
  {
    id: 3,
    name: 'MICHELIN Defender LTX',
    category: 'Tires',
    price: '$189/ea',
    rating: 4.9,
    reviews: 5412,
    desc: 'What we run on our tow vehicle. Outstanding all-season traction and wear.',
    badge: 'Top Rated',
    link: '#affiliate-michelin',
    emoji: '🛞',
  },
];

export const videos = [
  {
    id: 1,
    title: 'Full Tour: Our 36-ft Forest River After 2 Years of Full-Time Living',
    thumb: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=600&q=80',
    duration: '18:42',
    views: '142K',
    channel: 'Open Road RV',
  },
  {
    id: 2,
    title: 'Top 10 Free Campsites in the American Southwest',
    thumb: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=600&q=80',
    duration: '24:10',
    views: '89K',
    channel: 'Open Road RV',
  },
  {
    id: 3,
    title: 'How We Installed Solar + Lithium in One Weekend',
    thumb: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600&q=80',
    duration: '31:05',
    views: '211K',
    channel: 'Open Road RV',
  },
];

export const destinations = [
  { id: 1, name: 'Moab, Utah',       image: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=600&q=80', count: 14 },
  { id: 2, name: 'Smokies, TN',      image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&q=80', count: 9  },
  { id: 3, name: 'Big Bend, TX',     image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80', count: 7  },
  { id: 4, name: 'Olympic, WA',      image: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&q=80', count: 11 },
  { id: 5, name: 'Acadia, ME',       image: 'https://images.unsplash.com/photo-1414609245224-afa02bfb3fda?w=600&q=80', count: 6  },
  { id: 6, name: 'Glacier, MT',      image: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=600&q=80', count: 8  },
];

export const sampleComments = [
  { id: 1, name: 'Randy T.', avatar: 'https://i.pravatar.cc/40?img=5',  text: 'Drove through Yellowstone last fall — this guide is spot on. The Pebble Creek campground tip saved us!', time: '2 days ago', likes: 18 },
  { id: 2, name: 'Connie B.', avatar: 'https://i.pravatar.cc/40?img=44', text: 'Finally someone writing honest RV content. Subscribed immediately.', time: '4 days ago', likes: 11 },
  { id: 3, name: 'Marcus W.', avatar: 'https://i.pravatar.cc/40?img=68', text: 'The solar breakdown is incredible. Bookmarked this for our conversion project this winter.', time: '1 week ago', likes: 24 },
];
